### ISSUE TITLE
using resolve.root for app code

### ISSUE THREAD

**Issue by aaronjensen** [jeffling/wallaby-webpack#13]
If I use `resolve.root` for my app code, wallaby doesn't see to pick up changes to files that I require via `require('myfile')` (as opposed to `require('../app/myfile')`.

Is there something I can do to set resolve.root to the wallaby cache version of my app dir?

**Comment by aaronjensen** [comment]
I figured it out.

Instead of:

``` js
resolve.root = path.resolve(__dirname, 'app')
```

I can do:

``` js
resolve.modulesDirectories = ['js']
```

**Comment by aaronjensen** [comment]
I'm going to reopen, ideally there's a way to still use `root` as the semantics are different. If I can get access to the cache path, I can set the full path.

**Comment by ArtemGovorov** [comment]
You may use the parameter of your [bootstrap function](http://wallabyjs.com/docs/config/bootstrap.html) (the function executes before any tests in each worker) to get the cache folder (`projectCacheDir`). Would it suffice?

**Comment by ArtemGovorov** [comment]
Sorry, I didn't realise you were talking about Webpack until I have seen what repo this issue is in. The [main configuration function (the one config object gets returned from)](http://wallabyjs.com/docs/config/overview.html) parameter has the same `projectCacheDir` property that you may use to get the cache folder path.

**Comment by aaronjensen** [comment]
Awesome, yeah, I forgot to update the issue by I discovered this as well. Thanks! Wallaby is amazing btw.

For posterity:

``` js
var babel = require('babel');
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.wallaby.config');
var path = require('path');

module.exports = function(wallaby) {
  webpackConfig.resolve.root = path.join(wallaby.projectCacheDir, 'app');
  var wallabyPostprocessor = wallabyWebpack(webpackConfig);

  return {...}
};
```

**Comment by ArtemGovorov** [comment]
@aaronjensen Awesome, thanks!
