### ISSUE TITLE
Graceful-fs deprecated for new node releases

### ISSUE THREAD

**Issue by NickClark** [jeffling/wallaby-webpack#16]
I'm not sure yet if this is going to break anything (just started trying out Wallabyjs), but thought I'd put it on the radar. When installing on node 5 `wallaby-webpack` npm gives the following warning:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

**Comment by ArtemGovorov** [comment]
Thanks for the report, fixed in wallaby-webpack v.0.0.16.
