### ISSUE TITLE
webpack-wallaby now breaks in Webpack 2.1.0-beta.23+

### ISSUE THREAD

**Issue by bfricka** [jeffling/wallaby-webpack#19]
As webpack inches closer and closer to 2, uptake is increasing due to the awesome new native ES6 support. In webpack 2.1.0-beta.22 and below, older configurations were still supported, but since beta.23 the new schema is now enforced and wallaby-webpack completely breaks as a result.

The primary issue has seems to be due to webpack-wallaby's use of `resolve.modulesDirectories`, which has been deprecated along with `resolve.root` and `resolve.fallback` to a single option: `modules: string[]`. See the [migration docs](http://webpack.js.org/how-to/upgrade-from-webpack-1/) for additional info.

If you accept PRs I can implement something that fixes this.

**Comment by ArtemGovorov** [comment]
@bfricka Thanks for bringing it up! We have discovered the issue just recently too and are already working on it. Shouldn't take too long.

**Comment by ArtemGovorov** [comment]
The fix is published in `wallaby-webpack@0.0.24`.
