### ISSUE TITLE
updating to webpack@v2.2.0-rc.5 breaks wallaby tests

### ISSUE THREAD

**Issue by pndewit** [jeffling/wallaby-webpack#20]
Hi,

I just updated webpack from webpack 2.2.0-rc.3 to webpack 2.2.0 and my wallaby suddenly started complaining: `ReferenceError: Can't find variable: __webpack_exports__`.

I did a little debugging and found out that the issue was introduced in webpack 2.2.0-rc.5. Taking a closer look at the error and the changes introduced in webpack 2.2.0-rc.5 I found out that this line in `webpack/lib/dependencies/HarmonyDetectionParserPlugin.js` is breaking things: `module.exportsArgument = "__webpack_exports__";`. Commenting out that line fixes the issues and look more closely at webpack I noticed that when `module.exportsArgument` is not set, it takes `exports` as fallback.

I am using the latest wallaby-webpack (0.0.30).

**Comment by ArtemGovorov** [comment]
Is there any way I could reproduce the issue (to verify my fix)?

**Comment by pndewit** [comment]
Good point. I am working based on this project:
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack

You could try to clone and update its dependencies. It should break things.

**Comment by pndewit** [comment]
Just verified, it gives me the same errors there. :)

**Comment by ArtemGovorov** [comment]
Thanks for the repo and the error analysis! I have published `wallaby-webpack@0.0.31` that fixes the issue, please update the package.

**Comment by pndewit** [comment]
Thank you so much for the insanely quick replies and fix! Just verified that `0.0.31` fixes the issue! 👍
