### ISSUE TITLE
npm WARN deprecated minimatch@2.0.1: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by adoardper** [jeffling/wallaby-webpack#21]
Your package uses a deprecated and vulnerable version of minimatch, can you please update:

npm WARN deprecated minimatch@2.0.1: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

├─┬ wallaby-webpack@0.0.33
│ └── minimatch@2.0.1

**Comment by ArtemGovorov** [comment]
Done.
