### ISSUE TITLE
Wallaby webpack resolve.modules doesn't seem to resolve to modules.

### ISSUE THREAD

**Issue by nathanvale** [jeffling/wallaby-webpack#23]
Hi I have a webpack config file working in my karma config file that resolve modules to the root of the project so from anywhere in my project I can import like this

import {
  User
} from 'components/icons/FontAwesomeIcon';

instead of 

import {
  User
} from '../../../../../components/icons/FontAwesomeIcon';

npm test works and resolve is fine but my wallaby config cant seem to resolve to it.

The configs are almost identical

https://github.com/nathanvale/react-enterprise/blob/master/app/test/karma.conf.js

https://github.com/nathanvale/react-enterprise/blob/master/wallaby.js

Are you able to see where I am going wrong here?

i really dont want to be seeing messages like 

​​Error: Cannot find module "components/icons/FontAwesomeIcon"​​

Thanks!

**Comment by ArtemGovorov** [comment]
You [need to point `resolve.modules` paths to the the wallaby cache folder](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder). You may quickly try by moving the `config` under  `module.exports = function (wallaby) {` and replacing the local project path with the wallaby cache path (for project code, but not for node modules):

```javascript
const PATHS = require('./webpack/paths');

...

module.exports = function (wallaby) {

  PATHS.app = PATHS.app.replace(process.cwd(), wallaby.projectCacheDir);
  PATHS.test = PATHS.test.replace(process.cwd(), wallaby.projectCacheDir);

  var config = { ...

...
```

**Comment by nathanvale** [comment]
Thanks for your prompt support. This solved my problem.
