### ISSUE TITLE
http.IncomingMessage.prototype is undefined

### ISSUE THREAD

**Issue by pearljamik** [jeffling/wallaby-webpack#25]
`var req = Object.create(http.IncomingMessage.prototype)`
 
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
at http://localhost:62625/____wallaby-bundle.js?1501265946287&wallabyFileId=bundle:219253
```

**Comment by ArtemGovorov** [comment]
Could you please share:
- your wallaby.js config,
- your webpack config,
- your package.json,
- the line where you import `http`.

**Comment by ArtemGovorov** [comment]
Closing the issue as being inactive for a few days. If it's still a valid issue for you, please provide the details requested above.
