### ISSUE TITLE
Vulnerable version of lodash

### ISSUE THREAD

**Issue by luciavelasco** [jeffling/wallaby-webpack#29]
<img width="651" alt="screen shot 2018-05-15 at 16 48 36" src="https://user-images.githubusercontent.com/14294127/40068209-fc4b1614-585f-11e8-89f0-2711b6c827ed.png">

https://nodesecurity.io/advisories/577

To reproduce, run `$npm audit`?

**Comment by ArtemGovorov** [comment]
Thanks for the report. Fixed and published in v3.9.8.
