### ISSUE TITLE
ES6 import syntax not working in spec file

### ISSUE THREAD

**Issue by okonet** [jeffling/wallaby-webpack#7]
ES6 `import` in the spec file doesn't get resolved to the file.

Rewriting using `require` works fine.

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue. I have created this [sample repo](https://github.com/wallabyjs/wallaby-webpack-sample) with ES6 `import` (via babel), can you have a look to see how is it different from your case?

**Comment by okonet** [comment]
Seems like `export default` syntax is the problem. I've changed the source file in the sample repo to be:

```
export default class Person {
  constructor(name) {
    this.name = name;
  }
}
```

and it failed.

**Comment by okonet** [comment]
Also it seems to be webpack unrelated? Should it be moved to the wallaby-public?

**Comment by ArtemGovorov** [comment]
@okonet Thanks, I will have a look. Regarding the issue, yep it should ideally be in wallaby-public, but I don't know how to move issues on GitHub between repos, is it even possible?

**Comment by okonet** [comment]
I've reported it again here: https://github.com/wallabyjs/public/issues/55
